### ISSUE TITLE
email regex is to restrictive

### ISSUE THREAD

**Issue by wodka** [perscrew/react-native-form-validator#29]
Hi, 

it would be good to use a more complete regex for the email validation like `/^(([^<>()\[\]\\.,;:\s@"]+(\.[^<>()\[\]\\.,;:\s@"]+)*)|(".+"))@((\[[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\.[0-9]{1,3}\])|(([a-zA-Z\-0-9]+\.)+[a-zA-Z]{2,}))$/` (copied from https://stackoverflow.com/questions/46155/how-to-validate-an-email-address-in-javascript)

**Comment by perscrew** [comment]
Hi ! Good suggestion, you could open a pull request with this modification, I will accept the changes 💯

**Comment by wodka** [comment]
Ok, will do that on Monday

**Comment by wodka** [comment]
as promised :)
