### ISSUE TITLE
A new version with equalPassword

### ISSUE THREAD

**Issue by phoenix214** [perscrew/react-native-form-validator#49]
I installed the latest version 0.3.2 using npm install but it doesn't have the equalPassword in defaultRules.js.
Can you help me?

**Comment by arochedy** [comment]
I confirm I have the same problem

**Comment by perscrew** [comment]
Hi, sorry I'm going to publish the version on npm. I was really busy lately ^^.

**Comment by perscrew** [comment]
Version 0.3.3 has been published

**Comment by phoenix214** [comment]
Thank you, I just installed the new version and implemented the equalPassword check based on the documentation. But it's not working.

`const {
			name,
			email,
			birthdate,
			password,
			phoneNumber,
		} = this.state;

		this.validate({
			name: { required: true },
			birthdate: { date: 'MM/DD/YYYY' },
			password: { minlength: 3 },
			confirmPassword: { minlength: 3, equalPassword: password },
			email: { email: true, required: true },
		});`
Can you have a look on this?

**Comment by arochedy** [comment]
Hi, 

you have to do like this : 

	this.validate({
		name: { required: true },
		birthdate: { date: 'MM/DD/YYYY' },
		password: { minlength: 3 },
		confirmPassword: { minlength: 3, equalPassword: this.state.password }, //add this.state 
		email: { email: true, required: true },
	});`

**Comment by phoenix214** [comment]
Just tried it. Still not working.

**Comment by phoenix214** [comment]
@arochedy I found the issue and created a PR. Can you please merge it and create a new version? Thank you.
